version: '2.30.3'

services:
  db:
    image: postgres:17
    container_name: db
    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: ./django-project/
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - ENVIRONMENT_ENGINE=django.db.backends.postgresql
      - POSTGRES_PORT=5432

volumes:
  postgres_data:
