RECIPE = [
    {
        'title': 'title_1',
        'description': 'description_1',
        ingredients: 'ingredients_1',
        instructions: 'instructions_1',
        category: 'category_1',
        created_at: '2024.11.1',
        created_by: 'author_1',
    },
    {
        'title': 'title_2',
        'description': 'description_2',
        ingredients: 'ingredients_2',
        instructions: 'instructions_2',
        category: 'category_2',
        created_at: '2024.11.2',
        created_by: 'author_2',
    },
    {
        'title': 'title_3',
        'description': 'description_3',
        ingredients: 'ingredients_3',
        instructions: 'instructions_3',
        category: 'category_3',
        created_at: '2024.11.3',
        created_by: 'author_3',
    },
    {
        'title': 'title_4',
        'description': 'description_4',
        ingredients: 'ingredients_4',
        instructions: 'instructions_4',
        category: 'category_4',
        created_at: '2024.11.4',
        created_by: 'author_4',
    },
    {
        'title': 'title_5',
        'description': 'description_5',
        ingredients: 'ingredients_5',
        instructions: 'instructions_5',
        category: 'category_5',
        created_at: '2024.11.5',
        created_by: 'author_5',
    },
    {
        'title': 'title_6',
        'description': 'description_6',
        ingredients: 'ingredients_6',
        instructions: 'instructions_6',
        category: 'category_6',
        created_at: '2024.11.6',
        created_by: 'author_6',
    },
    {
        'title': 'title_7',
        'description': 'description_7',
        ingredients: 'ingredients_7',
        instructions: 'instructions_7',
        category: 'category_7',
        created_at: '2024.11.7',
        created_by: 'author_7',
    },
    {
        'title': 'title_8',
        'description': 'description_8',
        ingredients: 'ingredients_8',
        instructions: 'instructions_8',
        category: 'category_8',
        created_at: '2024.11.8',
        created_by: 'author_8',
    },
    {
        'title': 'title_9',
        'description': 'description_9',
        ingredients: 'ingredients_9',
        instructions: 'instructions_9',
        category: 'category_9',
        created_at: '2024.11.9',
        created_by: 'author_9',
    },
]
